version: "2"
run:
  go: "1.24"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoinits
    - godot
    - godox
    - gomoddirectives
    - ireturn
    - lll
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - godoclint
  settings:
    gocritic:
      disabled-checks:
        - commentedOutCode
        - commentFormatting
        - hugeParam
        - typeDefFirst
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - telegram-bot-api
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ar2rworld/golang-telegram-video-downloader)
        - blank
        - dot
      custom-order: true
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ar2rworld/golang-telegram-video-downloader
  exclusions:
    generated: lax
    paths:
      - telegram-bot-api
      - third_party$
      - builtin$
      - examples$
