# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/golangci/golangci-lint
  rev: v1.58.2
  hooks:
  - id: golangci-lint
    entry: golangci-lint run --fix
    require_serial: true
    verbose: true
