name: Build and publish a Docker image

on:
  push:
    branches:
    - releases/**

env:
  REGISTRY: ghcr.io
  ghcr_user: ${{ github.actor }}
  IMAGE_NAME: ${{ github.repository }}
  CR_PAT: ${{ secrets.ACTION_SECRET }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        run: echo "$CR_PAT" | docker login ghcr.io -u "$ghcr_user" --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
