name: ci

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Install dependencies
        run: go get ./app
      - name: Build
        run: go build -o osynetelegramvideodownloader ./app
      - name: Test
        run: go test ./app/cleaner
